"""teste

Revision ID: 98567cc90247
Revises: c8754cf92f95
Create Date: 2026-08-29 17:48:27.337078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98567cc90247'
down_revision: Union[str, Sequence[str], None] = 'c8754cf92f95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('email', sa.String(), nullable=False))
    op.drop_constraint(op.f('empresas_senha_key'), 'empresas', type_='unique')
    op.create_unique_constraint('empresas_email_key', 'empresas', ['email'])
    op.drop_column('empresas', 'senha')
    op.add_column('test', sa.Column('idade', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'idade')
    op.add_column('empresas', sa.Column('senha', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('empresas_email_key', 'empresas', type_='unique')
    op.create_unique_constraint(op.f('empresas_senha_key'), 'empresas', ['senha'], postgresql_nulls_not_distinct=False)
    op.drop_column('empresas', 'email')
    # ### end Alembic commands ###
