"""tabela-pessoas-2

Revision ID: c8754cf92f95
Revises: d34b9254f315
Create Date: 2026-08-29 17:04:59.365955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8754cf92f95'
down_revision: Union[str, Sequence[str], None] = 'd34b9254f315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_empresa', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('data_criação', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='empresas2_pkey'),
    sa.UniqueConstraint('email', name='empresas2_email_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empresas2')
    # ### end Alembic commands ###
