"""completando tudo

Revision ID: d34b9254f315
Revises: 8be974ae31dd
Create Date: 2026-08-29 16:10:22.731828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd34b9254f315'
down_revision: Union[str, Sequence[str], None] = '8be974ae31dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # with op.batch_alter_table('empresas', schema=None) as batch_op -> tipo o begin e commit


    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('senha', sa.String(), nullable=False))
    op.drop_constraint(op.f('empresas_email_key'), 'empresas', type_='unique')
    op.create_unique_constraint('empresas_senha_key', 'empresas', ['senha'])
    op.drop_column('empresas', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('empresas_senha_key', 'empresas', type_='unique')
    op.create_unique_constraint(op.f('empresas_email_key'), 'empresas', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('empresas', 'senha')
    # ### end Alembic commands ###
